#!/usr/bin/env bash

WEBDEVDATA_DIR=${1:-$WEBDEVDATA_DIR}
WDDTOOS_DIR=${WDDTOOS_DIR:-/usr/local/bin}
WDD_SELECT=$WDDTOOS_DIR/wdd_select
SELECTOR="link"

find $WEBDEVDATA_DIR/ -name "*tml.txt" |
  $WDD_SELECT -attrs=rel,href,media "$SELECTOR" > /tmp/link_tags.csv

iconv -c -f MAC -t UTF8 /tmp/link_tags.csv

